export const PROTOCOL_TAGS = [
  'Adult',
  'Cardiac',
  'Dysrhythmias',
  'Environmental',
  'General Care',
  'Medical',
  'Neurological',
  'OB / GYN',
  'Operations',
  'Pediatric',
  'Procedures',
  'Respiratory',
  'Resuscitation',
  'Toxins',
  'Trauma',
]

export const MEDICATION_TAGS = [
  'ACLS',
  'adult',
  'allergy',
  'cardiac',
  'crush',
  'hypertension',
  'hypoglycemia',
  'hypotension',
  'nausea',
  'overdose',
  'pain',
  'pediatric',
  'respiratory',
  'sedation',
  'seizure',
]
